name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker-build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/week2devops:latest .

      # Step 4: Push Docker Image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/week2devops:latest

      # Step 5: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/week2devops:latest

            sudo docker stop mywebsite || true

            sudo docker rm mywebsite || true

            sudo docker run -d \
              --name mywebsite \
              -p 80:80 \
              ${{ secrets.DOCKER_USERNAME }}/week2devops:latest